### ISSUE TITLE
Issue Regarding Alarm List

### ISSUE THREAD

**Issue by himanshu717171** [geisterfurz007/random-alarm#13]
Target of URI hasn't been generated: 'alarm_list.g.dart'.
Try running the generator that will generate the file referenced by the URI.

This is the error showing on alarm_list.dart and few more pages like alarm_status.dart, searchable_selection.dart.
I don't understand why in my PC "part 'searchable_selection.g.dart';" like this packages are not working..

Please solve this issue

**Comment by mvarendorff** [comment]
Have you tried doing what the error tells you?

> Try running the generator that will generate the file referenced by the URI.

-> Run `flutter packages pub run build_runner build --delete-conflicting-outputs` to generate the `.g.dart` files.

Both mobx and json_serializable rely on generated files that are created based on annotations within the code.  
You can find more information on those two packages on the respective pub.dev pages: [json_serializable](https://pub.dev/packages/json_serializable) and [mobx_codegen](https://pub.dev/packages/mobx_codegen).  
More information on the build_runner and why it's used can be found on the [build_runner](https://pub.dev/packages/build_runner) package page.

**Comment by mvarendorff** [comment]
This hasn't gotten a response in a week; closing. Feel free to reopen if the suggestion above didn't resolve your problem. When doing so, provide detailed steps to reproduce.

**Comment by Sawan-Kag** [comment]
I tryed   the command --> `flutter packages pub run build_runner build --delete-conflicting-outputs`

but  geting error

can you help me to solve this .

`┌─[✗]─[sawan@parrot]─[~/Desktop/random-alarm-master]
└──╼ $flutter packages pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 374ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 13.2s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 809ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 3ms

[INFO] Running build...
[WARNING] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.9.0
SDK language version: 2.12.0

If you are getting this message and have the latest analyzer please file
an issue at https://github.com/dart-lang/sdk/issues/new with the title
"No published analyzer available for language version 2.12.0".
Please search the issue tracker first and thumbs up and/or subscribe to
existing issues if present to avoid duplicates.

[INFO] Generating SDK summary...
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[SEVERE] json_serializable:json_serializable on lib/screens/alarm_screen/alarm_screen.dart:

Bad state: Unexpected diagnostics:
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:138:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:157:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:152:3 - Members of classes can't be declared to be 'abstract'.
/home/sawan/STUDIO/flutter/bin/cache/dart-sdk/lib/async/stream_controller.dart:145:3 - Members of classes can't be declared to be 'abstract'.
[INFO] 1.9s elapsed, 1/17 actions completed.
[INFO] 3.0s elapsed, 1/17 actions completed.
[INFO] 4.1s elapsed, 1/17 actions completed.
[INFO] 5.2s elapsed, 1/17 actions completed.
[INFO] 6.3s elapsed, 1/17 actions completed.
[INFO] 7.4s elapsed, 1/17 actions completed.
[INFO] 8.5s elapsed, 1/17 actions completed.
[INFO] 9.6s elapsed, 1/17 actions completed.
[INFO] 10.7s elapsed, 1/17 actions completed.
[INFO] 11.8s elapsed, 1/17 actions completed.
[INFO] 12.9s elapsed, 1/17 actions completed.
[INFO] 14.0s elapsed, 1/17 actions completed.
[INFO] 15.1s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.0s, waiting on:
  - json_serializable:json_serializable on lib/screens/home_screen/home_screen.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/edit_alarm.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/components/music_list_item.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/components/edit_alarm_music.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/components/playlist_list_item.dart
  .. and 11 more

[INFO] 16.9s elapsed, 1/17 actions completed.
[INFO] 17.9s elapsed, 1/17 actions completed.
[INFO] 19.0s elapsed, 1/17 actions completed.
[INFO] 20.0s elapsed, 1/17 actions completed.
[INFO] 21.1s elapsed, 1/17 actions completed.
[INFO] 22.2s elapsed, 1/17 actions completed.
[INFO] 23.3s elapsed, 1/17 actions completed.
[INFO] 24.4s elapsed, 1/17 actions completed.
[INFO] 25.5s elapsed, 1/17 actions completed.
[INFO] 26.6s elapsed, 1/17 actions completed.
[INFO] 27.7s elapsed, 1/17 actions completed.
[INFO] 28.8s elapsed, 1/17 actions completed.
[INFO] 29.9s elapsed, 1/17 actions completed.
[INFO] 30.9s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - json_serializable:json_serializable on lib/screens/home_screen/home_screen.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/edit_alarm.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/components/music_list_item.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/components/edit_alarm_music.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/components/playlist_list_item.dart
  .. and 11 more

[INFO] 32.0s elapsed, 1/17 actions completed.
[INFO] 33.1s elapsed, 1/17 actions completed.
[INFO] 34.2s elapsed, 1/17 actions completed.
[INFO] 35.2s elapsed, 1/17 actions completed.
[INFO] 36.3s elapsed, 1/17 actions completed.
[INFO] 37.3s elapsed, 1/17 actions completed.
[INFO] 38.4s elapsed, 1/17 actions completed.
[INFO] 39.5s elapsed, 1/17 actions completed.
[INFO] 40.6s elapsed, 1/17 actions completed.
[INFO] 41.7s elapsed, 1/17 actions completed.
[INFO] 42.8s elapsed, 1/17 actions completed.
[INFO] 43.9s elapsed, 1/17 actions completed.
[INFO] 45.0s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - json_serializable:json_serializable on lib/screens/home_screen/home_screen.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/edit_alarm.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/components/music_list_item.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/components/edit_alarm_music.dart
  - json_serializable:json_serializable on lib/screens/edit_alarm/components/playlist_list_item.dart
  .. and 11 more

[INFO] 47.1s elapsed, 1/17 actions completed.
[INFO] 48.2s elapsed, 1/17 actions completed.
[INFO] 49.3s elapsed, 1/17 actions completed.
[INFO] 50.4s elapsed, 1/17 actions completed.
[INFO] 51.5s elapsed, 1/17 actions completed.
[INFO] 52.6s elapsed, 1/17 actions completed.
[INFO] 53.7s elapsed, 1/17 actions completed.
[INFO] 54.8s elapsed, 1/17 actions completed.
[INFO] 55.9s elapsed, 1/17 actions completed.
^C┌─[sawan@parrot]─[~/Desktop/random-alarm-master]
└──╼ $
`

**Comment by mvarendorff** [comment]
I can highly recommend following the advice in the error message once again:

> Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

In general Flutter provides developers with extremely detailed errors explaining cause and potential solutions.
